local builtin = require('telescope.builtin')
vim.keymap.set('n', ',a', builtin.find_files, {})
vim.keymap.set('n', ',s', function()
  vim.keymap.set('n', '<C-p>', builtin.git_files, {})
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end)
